# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(480, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(390, 290, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(390, 250, 75, 23))
        self.pushButton_about.setObjectName("pushButton_about")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 351, 51))
        self.groupBox.setObjectName("groupBox")
        self.label_putkanji = QtWidgets.QLabel(self.groupBox)
        self.label_putkanji.setGeometry(QtCore.QRect(10, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_putkanji.setFont(font)
        self.label_putkanji.setText("")
        self.label_putkanji.setObjectName("label_putkanji")
        self.pushButton_answer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_answer.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(110, 290, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(300, 290, 75, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 351, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_putanswer = QtWidgets.QLabel(self.groupBox_2)
        self.label_putanswer.setGeometry(QtCore.QRect(10, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label_putanswer.setFont(font)
        self.label_putanswer.setText("")
        self.label_putanswer.setObjectName("label_putanswer")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 351, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_putsubject = QtWidgets.QLabel(self.groupBox_3)
        self.label_putsubject.setGeometry(QtCore.QRect(10, 20, 331, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        font.setStrikeOut(False)
        self.label_putsubject.setFont(font)
        self.label_putsubject.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_putsubject.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_putsubject.setText("")
        self.label_putsubject.setObjectName("label_putsubject")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 20, 71, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_N1 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_N1.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton_N1.setObjectName("radioButton_N1")
        self.radioButton_N2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_N2.setGeometry(QtCore.QRect(10, 40, 83, 16))
        self.radioButton_N2.setObjectName("radioButton_N2")
        self.radioButton_N3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_N3.setGeometry(QtCore.QRect(10, 60, 83, 16))
        self.radioButton_N3.setObjectName("radioButton_N3")
        self.radioButton_N4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_N4.setGeometry(QtCore.QRect(10, 80, 83, 16))
        self.radioButton_N4.setObjectName("radioButton_N4")
        self.radioButton_N5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_N5.setGeometry(QtCore.QRect(10, 100, 83, 16))
        self.radioButton_N5.setObjectName("radioButton_N5")
        self.groupBox_4.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_about.raise_()
        self.groupBox.raise_()
        self.pushButton_answer.raise_()
        self.pushButton_next.raise_()
        self.pushButton_reset.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.pushButton_exit.clicked.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "背單字v1.0"))
        self.pushButton_exit.setText(_translate("mainWindow", "離開(&Q)"))
        self.pushButton_about.setText(_translate("mainWindow", "關於我(&I)"))
        self.groupBox.setTitle(_translate("mainWindow", "日文漢字"))
        self.pushButton_answer.setText(_translate("mainWindow", "解答(&A)"))
        self.pushButton_next.setText(_translate("mainWindow", "下一題(&N)"))
        self.pushButton_reset.setText(_translate("mainWindow", "重置(&T)"))
        self.groupBox_2.setTitle(_translate("mainWindow", "中文"))
        self.groupBox_3.setTitle(_translate("mainWindow", "日文仮名"))
        self.label_putsubject.setToolTip(_translate("mainWindow", "題目在此"))
        self.groupBox_4.setTitle(_translate("mainWindow", "等級"))
        self.radioButton_N1.setText(_translate("mainWindow", "N&1"))
        self.radioButton_N2.setText(_translate("mainWindow", "N2"))
        self.radioButton_N3.setText(_translate("mainWindow", "N3"))
        self.radioButton_N4.setText(_translate("mainWindow", "N4"))
        self.radioButton_N5.setText(_translate("mainWindow", "N5"))
